game = "chess"
mcts_batch_size = 1
mcts_simulations = 800
full_search_probability = 1
resignation_enabled = false
fpu_reduction = 0.33
network_arch = "legacy"
chess_encoder_history = 0

[puct]
dirichlet_epsilon = 0.0
