#ifndef ALPHAZERO_INFERENCE_SERVER_MODEL_WRAPPER_CONNECT4_MODEL_WRAPPER_HPP
#define ALPHAZERO_INFERENCE_SERVER_MODEL_WRAPPER_CONNECT4_MODEL_WRAPPER_HPP

#include "model_wrapper.hpp"
#include <memory>

std::shared_ptr<ModelWrapper> get_connect4_model_wrapper();

#endif // ALPHAZERO_INFERENCE_SERVER_MODEL_WRAPPER_CONNECT4_MODEL_WRAPPER_HPP
