name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  LIBTORCH_VERSION: "2.7.1"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests doit

    - name: Download and Extract LibTorch
      run: |
        wget -q https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-${{ env.LIBTORCH_VERSION }}%2Bcpu.zip -O libtorch.zip
        unzip -q libtorch.zip
        echo "LIBTORCH_PATH=$PWD/libtorch" >> $GITHUB_ENV

    - name: Setup vcpkg and install C++ dependencies
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install spdlog nlohmann-json nlohmann-json-schema-validator asio crow cpputest

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=${{ env.LIBTORCH_PATH }} -DBUILD_TESTS=ON -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build C++ components
      run: |
        cd build
        make -j$(nproc)

    - name: Format Checks (C++ & Python)
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format fd-find
        doit check_cpp_format
        doit check_python_format

    - name: Python Lint Check
      run: |
        doit check_python_lint

    - name: C++ Tests
      run: |
        doit test_cpp

    - name: Python Tests
      run: |
        doit test_python
